// File generated by FlutterFire CLI for project hirehub-app-de9ad.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgkgdY3vpKss2HpcaoGvjsdA9MWt3iuNo',
    appId: '1:220903275485:android:cb693f2ae64a652f9d9434',
    messagingSenderId: '220903275485',
    projectId: 'hirehub-app-de9ad',
    storageBucket: 'hirehub-app-de9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebeFASs-WX5uoucZ6Qxhax4etMgcaxkw',
    appId: '1:220903275485:ios:4cea6e20feb113719d9434',
    messagingSenderId: '220903275485',
    projectId: 'hirehub-app-de9ad',
    storageBucket: 'hirehub-app-de9ad.firebasestorage.app',
    iosBundleId: 'com.example.jobSeeker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAolJPDftTmZaX0kcoLaQoGURM8RDUQog4',
    appId: '1:220903275485:web:44081af556963a119d9434',
    messagingSenderId: '220903275485',
    projectId: 'hirehub-app-de9ad',
    authDomain: 'hirehub-app-de9ad.firebaseapp.com',
    storageBucket: 'hirehub-app-de9ad.firebasestorage.app',
    measurementId: 'G-EKHG2D6DGQ',
  );
}
